export const EXERCISE_REPOSITORY_SEARCH = "EXERCISE_REPOSITORY_SEARCH";

export const EXERCISES_LOAD = "EXERCISES_LOAD";

export const EXERCISE_LOAD = "EXERCISE_LOAD";

export const TURN_ON_LOADER = "TURN_ON_LOADER";

export const TURN_OFF_LOADER = "TURN_OFF_LOADER";
